import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";

import localFont from "next/font/local";
import { Rubik, Inter, Rancho } from "next/font/google";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const rancho = Rancho({
  subsets: ["latin"],
  variable: "--font-rancho",
  weight: "400",
});

export const metadata: Metadata = {
  title: "KeY2Moon Solutions",
  description: "Generated by KeY2Moon Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} ${inter.variable} ${rancho.variable} font-inter antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
